apiVersion: apps/v1
kind: Deployment
metadata:
  name: maestro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maestro
  template:
    metadata:
      labels:
        app: maestro
    spec:
      containers:
        - name: maestro
          image: maestro-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: maestro-service
spec:
  selector:
    app: maestro
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort