# MAESTRO SERVICE - Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maestro-service
  labels:
    app: maestro-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maestro-service
  template:
    metadata:
      labels:
        app: maestro-service
    spec:
      containers:
        - name: maestro-service
          image: maestro-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
---
# MAESTRO SERVICE - Service
apiVersion: v1
kind: Service
metadata:
  name: maestro-service
spec:
  selector:
    app: maestro-service
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
