# NOTIF SERVICE - Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notif-service
  labels:
    app: notif-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notif-service
  template:
    metadata:
      labels:
        app: notif-service
    spec:
      containers:
        - name: notif-service
          image: notif-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 6000
          env:
            - name: EMAIL_USER
              value: "joaomiko25@gmail.com"
            - name: EMAIL_PASS
              value: "shro vmth xwtf eupa"
---
# NOTIF SERVICE - Service
apiVersion: v1
kind: Service
metadata:
  name: notif-service
spec:
  selector:
    app: notif-service
  ports:
    - name: http
      port: 6000
      targetPort: 6000
  type: ClusterIP
