apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
  labels:
    app: task-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:   # 👈 FIXED: This now properly contains the containers block
      containers:
        - name: task-service
          image: task-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7000
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "microservicos"
            - name: DB_USER
              value: "joaomiko"
            - name: DB_PASS
              value: "joaogoodman"
---
apiVersion: v1
kind: Service
metadata:
  name: task-service
spec:
  selector:
    app: task-service
  ports:
    - name: http
      port: 7000
      targetPort: 7000
  type: ClusterIP
