apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: task-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: task-service
spec:
  selector:
    app: tasks
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
  type: NodePort
