# Dockerfile para o serviço de utilizadores
FROM node:14

WORKDIR /app

# Copiar o package.json e instalar as dependências
COPY package.json ./
RUN npm install

# Copiar o restante do código
COPY . .

# Expõe a porta do serviço de utilizadores
EXPOSE 5000

# Iniciar o serviço
CMD ["node", "userService.js"]
