services:
  maestro:
    build:
      context: ./Maestro
    container_name: maestro-service
    volumes:
      - ./Maestro/src:/Maestro/src
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - user
      - db
      - notif

  auth:
    build:
      context: ./Auth
    container_name: auth-service
    volumes:
      - ./Auth/src:/Auth/src
    ports:
      - "4000:4000"
    depends_on:
      - db

  user:
    build:
      context: ./User
    container_name: user-service
    volumes:
      - ./User/src:/User/src
    ports:
      - "5000:5000"
    depends_on:
      - db

  notif:
    build:
      context: ./Notif
    container_name: notif-service
    volumes:
      - ./Notif/src:/Notif/src
    ports:
      - "6000:6000"
    environment:
      - EMAIL_USER=joaomiko25@gmail.com
      - EMAIL_PASS=shro vmth xwtf eupa
      
  tasks:
      build:
        context: ./Tasks
      container_name: task-service
      volumes:
        - ./Tasks/src:/Tasks/src
      ports:
        - "7000:7000"
      depends_on:
        - db

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: joaomiko
      POSTGRES_PASSWORD: joaogoodman
      POSTGRES_DB: microservicos
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U joaomiko -d microservicos" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
