version: '3'
services:
  maestro:
    build:
      context: ./maestro
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - user

  auth:
    build:
      context: ./auth
    ports:
      - "4000:4000"
    volumes:
      - ./data/auth.sqlite:/app/db.sqlite

  user:
    build:
      context: ./user
    ports:
      - "5000:5000"
    volumes:
      - ./data/user.sqlite:/app/db.sqlite
    depends_on:
      - auth

volumes:
  data:
