services:
  maestro:
    build:
      context: ./maestro
    container_name: maestro-service
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - user
      - db

  auth:
    build:
      context: ./auth
    container_name: auth-service
    ports:
      - "4000:4000"
    depends_on:
      - db

  user:
    build:
      context: ./user
    container_name: user-service
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: joaomiko
      POSTGRES_PASSWORD: joaogoodman
      POSTGRES_DB: microservicos
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
