.version: '3.8'
services:
  user-service:
    build: ./user
    ports:
      - "3001:3000"
    networks:
      - app-net

  auth-service:
    build: ./auth
    ports:
      - "3002:3000"
    networks:
      - app-net
    depends_on:
      - user-service

networks:
  app-net:
